name: Ruby Linter

on:
  pull_request:
    paths:
      - '*.rb'
      - '!bin/**'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Run Standard Ruby linter
        run: bin/standardrb --no-fix --fail-fast
