---
name: Lint Code Base

on:
  pull_request:
    branches: [master]
    paths:
      - '*.rb'
      - '*.yml'
      - '.github/workflows/lint.yml'
      - '!bin/**'

jobs:
  standard:
    name: Standard
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Run Standard Ruby linter
        run: bin/standardrb --no-fix --fail-fast

      - name: Run Yaml linter
        run: |
          sudo apt-get install --fix-missing -qq --no-install-recommends yamllint
          yamllint ./
