---

name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    type: [ opened, synchronize, reopened, review_requested ]
    paths:
      - '**.gemfile'
      - '**.rb'
      - '.github/workflows/**'
      - '!bin/**'
  workflow_dispatch:

env:
  BUNDLE_GEMFILE: 'gemfiles/rails70_gems.rb'
  FERRUM_PROCESS_TIMEOUT: '40'
  WD_CACHE_TIME: '864000' # 10 days

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Functional Testing
    runs-on: ubuntu-22.04 # In order to install libvips 8.9+ version
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install libvips
        env:
          DEBIAN_FRONTEND: noninteractive
        run: sudo apt-get install -qq --no-install-recommends libvips libvips-dev libvips-tools

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0-preview3'
          bundler-cache: true

      - name: Run Tests with coverage
        env:
          COVERAGE: enabled
          RUBY_YJIT_ENABLE: 1
        run: bundle exec rake test

      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          retention-days: 1
          path: |
            test/fixtures/app/doc/screenshots/
            tmp/capybara/screenshots-diffs/

      - name: Upload Coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          retention-days: 1
          path: coverage

  matrix:
    name: Test Integration Rails & Ruby
    if: github.ref == 'refs/heads/master' || github.event.inputs ||
      github.event.pull_request.requested_reviewers.length > 0
    needs: [ 'test' ]
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    strategy:
      matrix:
        ruby-version: [ '3.2.0-preview3', '3.1', '3.0', '2.7', 'jruby', 'jruby-9.4.0.0' ]
        gemfile:
          - 'rails70_gems.rb'
          - 'rails61_gems.rb'
          - 'rails60_gems.rb'
        exclude:
          # We already tested last version
          - ruby-version: '3.2.0-preview3'
            gemfile: 'gemfiles/rails70_gems.rb'
          # JRuby < 9.4 is compatible with Ruby 2.6, but Rails 7 is compatible with Ruby 2.7+
          - ruby-version: 'jruby'
            gemfile: 'rails70_gems.rb'

    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Install libvips
        env:
          DEBIAN_FRONTEND: noninteractive
        run: sudo apt-get install -qq --no-install-recommends libvips libvips-dev libvips-tools

      - name: Run tests
        run: bundle exec rake test

  matrix-screenshot-driver:
    name: Test Integration Capybara & Image Drivers
    if: github.ref == 'refs/heads/master' || github.event.inputs ||
      github.event.pull_request.requested_reviewers.length > 0
    needs: [ 'test' ]

    strategy:
      matrix:
        screenshot-driver: [ vips, chunky_png ]
        capybara-driver: [ selenium_headless, selenium_chrome_headless, cuprite ]

    runs-on: ${{ matrix.capybara-driver == 'selenium_headless' && 'ubuntu-20.04' || 'ubuntu-22.04' }}

    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0-preview3'
          bundler-cache: true

      - name: Install libvips
        if: matrix.screenshot-driver == 'vips'
        env:
          DEBIAN_FRONTEND: noninteractive
        run: sudo apt-get install -qq --no-install-recommends libvips libvips-dev libvips-tools

      - name: Run tests
        run: bundle exec rake test:integration
        env:
          SCREENSHOT_DRIVER: ${{ matrix.screenshot-driver }}
          CAPYBARA_DRIVER: ${{ matrix.capybara-driver }}

      - name: Upload Screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: screenshots-${{ matrix.screenshot-driver }}-${{ matrix.capybara-driver }}
          retention-days: 1
          path: |
            test/fixtures/app/doc/screenshots/
            tmp/capybara/screenshots-diffs/
